### ISSUE TITLE
Encoding/Decoding issues

### ISSUE THREAD

**Issue by anton-dutov** [MrSmith33/cbor-d#4]
Code

```
import std.stdio;

import cbor;

void main()
{
        CborValue[CborValue] z;

        z[CborValue("key")] = CborValue("val");

        ubyte[] dst;
        dst.length = 4096;
        dst.length = encodeCbor(dst[], z);
        writeln(dst);
        writeln(dst.decodeCbor);
}
```

Output

```
[161, 129, 9, 129, 9]
CborValue(map, [CborValue(array, [CborValue(posinteger, 9)]):CborValue(array, [CborValue(posinteger, 9)])])
```

I'm confused, unexpected result

**Comment by MrSmith33** [comment]
Actually CborValue is used only for decoding. In your example CborValue was encoded as array (as all structures do)
Encoding string[string] type would give the needed result.
Now I am making new version, without CborValue. SAX-like decoding.

**Comment by anton-dutov** [comment]
But how to encode complex structs, like JSON items?

**Comment by MrSmith33** [comment]
Firstly you can use primitive encoding functions, like encodeInt, encodeArrayHeader/payload, encodeMap, or simply any structure/class/tuple via encodeCbor (which will maintain signature)

I've finished doing coding, now finishing docs/commit/examples.

Edit: You will be able to traverse json tree manually and output cbor without unnesesary allocations.
